name: Build and Publish Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker images
      run: |
        docker build -t ghcr.io/${{ github.repository }}:db ./db
        docker build -t ghcr.io/${{ github.repository }}:filebeat ./logs/filebeat
        docker build -t ghcr.io/${{ github.repository }}:app ./app

    - name: Push Docker images
      run: |
        docker push ghcr.io/${{ github.repository }}:db
        docker push ghcr.io/${{ github.repository }}:filebeat
        docker push ghcr.io/${{ github.repository }}:app

    - name: Verify the images
      run: |
        docker pull ghcr.io/${{ github.repository }}:db
        docker pull ghcr.io/${{ github.repository }}:filebeat
        docker pull ghcr.io/${{ github.repository }}:app
